// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1mbm0nodDrVbDSG0fGWJb2RRUMDkUV2E',
    appId: '1:161392494509:web:fafec5e98dfd83a05c0324',
    messagingSenderId: '161392494509',
    projectId: 'chak-ikk-ac2ea',
    authDomain: 'chak-ikk-ac2ea.firebaseapp.com',
    storageBucket: 'chak-ikk-ac2ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMgl1Hrke0pMza4vTznhp2wOmVtfovkUE',
    appId: '1:161392494509:android:a8f80bf1ce3c03c75c0324',
    messagingSenderId: '161392494509',
    projectId: 'chak-ikk-ac2ea',
    storageBucket: 'chak-ikk-ac2ea.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1mbm0nodDrVbDSG0fGWJb2RRUMDkUV2E',
    appId: '1:161392494509:web:dca063378ef947a45c0324',
    messagingSenderId: '161392494509',
    projectId: 'chak-ikk-ac2ea',
    authDomain: 'chak-ikk-ac2ea.firebaseapp.com',
    storageBucket: 'chak-ikk-ac2ea.firebasestorage.app',
  );
}
